# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: non-default-proc-mount-cue
  annotations:
    catalog.chainguard.dev/title: Disallow non-default /proc mounts
    catalog.chainguard.dev/labels: cue,workloads
    catalog.chainguard.dev/description: |
      The default /proc masks are set up to reduce attack surface, and should be required.

    catalog.chainguard.dev/learnMoreLink: https://kubernetes.io/docs/concepts/security/pod-security-standards/#baseline
spec:
  match:
  - version: "v1"
    resource: "pods"
  images: [glob: '**']
  authorities: [static: {action: pass}]
  mode: warn
  policy:
    includeSpec: true
    type: "cue"
    data: |
      #Allowed: "Default"
      spec: {
        initContainers: [...{
          securityContext: {
            procMount: #Allowed
          }
        }]
        containers: [...{
          securityContext: {
            procMount: #Allowed
          }
        }]
        ephemeralContainers: [...{
          securityContext: {
            procMount: #Allowed
          }
        }]
      }
