# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: non-default-proc-mount-rego
  annotations:
    catalog.chainguard.dev/title: Disallow non-default/proc-mounts
    catalog.chainguard.dev/labels: rego,workloads
    catalog.chainguard.dev/description: |
      The default /proc masks are set up to reduce attack surface, and should be required.

    catalog.chainguard.dev/learnMoreLink: https://kubernetes.io/docs/concepts/security/pod-security-standards/#baseline
spec:
  match:
  - version: "v1"
    resource: "pods"
  images: [glob: '**']
  authorities: [static: {action: pass}]
  mode: warn
  policy:
    includeSpec: true
    type: "rego"
    data: |
      package sigstore
      default isCompliant = false
      isCompliant {
        filteredContainers = [c | c := input.spec.containers[_]; c.securityContext.procMount != "Default"]
        filteredInitContainers = [c | c := input.spec.initContainers[_]; c.securityContext.procMount != "Default"]
        filteredEphemeralContainers = [c | c := input.spec.ephemeralContainers[_]; c.securityContext.procMount != "Default"]
        (count(filteredContainers) + count(filteredInitContainers) + count(filteredEphemeralContainers)) == 0
      }

