# Copyright 2023 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: cloudrun-serviceaccount-rego
  annotations:
    catalog.chainguard.dev/title: Disallow default service account
    catalog.chainguard.dev/labels: rego,cloudrun,workloads
    catalog.chainguard.dev/description: |
      Google recommends giving every Cloud Run service a dedicated identity by
      assigning it a user-managed service account instead of using the default
      service account.

    catalog.chainguard.dev/learnMoreLink: https://cloud.google.com/run/docs/securing/service-identity#per-service-identity
spec:
  match:
  - group: "serving.knative.dev"
    version: "v1"
    resource: "services"
  images: [glob: '**']
  authorities: [static: {action: pass}]
  mode: warn
  policy:
    includeSpec: true
    type: "rego"
    data: |
      package sigstore

      isCompliant[response] {
        not input.spec.template.spec.serviceAccountName

        response := {
          "result" : false,
          "error" : "serviceAccountName should be set to a non-default service account"
        }
      }

      isCompliant[response] {
        endswith(input.spec.template.spec.serviceAccountName, "-compute@developer.gserviceaccount.com")

        response := {
          "result" : false,
          "error" : "serviceAccountName should not use the Compute Engine service account"
        }
      }

      isCompliant[response] {
        not endswith(input.spec.template.spec.serviceAccountName, "-compute@developer.gserviceaccount.com")

        response := {
          "result" : true,
        }
      }
