# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: cilium-signed
  annotations:
    catalog.chainguard.dev/title: Cilium is signed
    catalog.chainguard.dev/description: |
      Enforce that the Cilium images are signed by the Cilium
      release's workload identity.

      The Cilium project added signing in their 1.13 release.
    catalog.chainguard.dev/labels: components
spec:
  images:
  - glob: index.docker.io/cilium/cilium*
  authorities:
  - keyless:
      url: https://fulcio.sigstore.dev
      identities:
      - issuer: https://token.actions.githubusercontent.com
        subjectRegExp: https://github\.com/cilium/cilium/\.github/workflows/build-images-releases\.yaml@refs/tags/v.*
    ctlog:
      url: https://rekor.sigstore.dev
