# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: keda-signed
  annotations:
    catalog.chainguard.dev/title: KEDA is signed
    catalog.chainguard.dev/description: |
      Enforce that the KEDA images are signed by the KEDA
      release's workload identity.
    catalog.chainguard.dev/labels: components
spec:
  images:
  - glob: ghcr.io/kedacore/**
  authorities:
  - keyless:
      url: https://fulcio.sigstore.dev
      identities:
      - issuer: https://token.actions.githubusercontent.com
        subjectRegExp: https://github\.com/kedacore/keda/\.github/workflows/release-build\.yml@refs/tags/v.*
    ctlog:
      url: https://rekor.sigstore.dev
