# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: kubernetes-signed
  annotations:
    catalog.chainguard.dev/title: Kubernetes images are signed
    catalog.chainguard.dev/description: |
      This policy verifies the signatures on upstream Kubernetes
      components verifying they were signed by the Kubernetes
      release infrastructure.
    catalog.chainguard.dev/labels: components
spec:
  images:
  - glob: registry.k8s.io/**
  authorities:
  - keyless:
      url: https://fulcio.sigstore.dev
      identities:
      - issuer: https://accounts.google.com
        subject: krel-trust@k8s-releng-prod.iam.gserviceaccount.com
    ctlog:
      url: https://rekor.sigstore.dev

