# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: linkerd-signed
  annotations:
    catalog.chainguard.dev/title: Linkerd is signed
    catalog.chainguard.dev/description: |
      Enforce that the Linkerd images are signed by the Linkerd
      release's workload identity.
    catalog.chainguard.dev/labels: components
spec:
  images:
  - glob: ghcr.io/linkerd/**
  authorities:
  - keyless:
      url: https://fulcio.sigstore.dev
      identities:
      - issuer: https://token.actions.githubusercontent.com
        subjectRegExp: https://github\.com/linkerd/linkerd2/\.github/workflows/release\.yml@refs/tags/.*
    ctlog:
      url: https://rekor.sigstore.dev
