# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: shipwright-signed
  annotations:
    catalog.chainguard.dev/title: Shipwright is signed
    catalog.chainguard.dev/description: |
      Enforce that the Shipwright images are signed by the Shipwright
      release's workload identity.
    catalog.chainguard.dev/labels: components
spec:
  images:
  - glob: ghcr.io/shipwright-io/build/**
  authorities:
  - keyless:
      url: https://fulcio.sigstore.dev
      identities:
      - issuer: https://token.actions.githubusercontent.com
        subject: https://github.com/shipwright-io/build/.github/workflows/release.yaml@refs/heads/main
    ctlog:
      url: https://rekor.sigstore.dev
